name: 'CI'

on: [ push, pull_request, workflow_dispatch ]

jobs:
  testLinux:
    name: 'PHP Unit'

    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3' ]
        dokuwiki-branch: [ 'master', 'stable' ]
        
      fail-fast: false


    uses: mprins/.github/.github/workflows/test.yml@test-workflow
    with:
        php-version: ${{ matrix.php-version }}
        dokuwiki-branch: ${{ matrix.dokuwiki-branch }}


